import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Next.js + Three.js Sample</title>
        <meta name="description" content="Next.js + Three.js Sample" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className + "min-h-[100vh] container mx-auto"}>
        {children}
      </body>
    </html>
  );
}
